# Generated by Django 5.0.7 on 2024-08-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('report', models.CharField(max_length=1024, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classic_tasks', to='abilities.outcome')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('xp', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_submit', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks', to='abilities.outcome')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('xp', models.IntegerField(default=0)),
                ('penalty_xp', models.IntegerField(default=0)),
                ('report', models.CharField(blank=True, max_length=1024, null=True)),
                ('penalty', models.IntegerField(choices=[(0.5, 'Half XP loose'), (1, 'Equal XP loose'), (2, 'Double XP loose'), (4, 'Four fold XP loose')], default=1)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_aborted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_tasks', to='abilities.outcome')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('xp', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('longest_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_submit', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tasks', to='abilities.outcome')),
            ],
        ),
    ]
