# Generated by Django 5.0.7 on 2024-08-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='report',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
