# Generated by Django 5.2.7 on 2025-10-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outcomes', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classic_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='count',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks', to='outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='count',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadline',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_tasks', to='outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='time',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tasks', to='outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='time',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
