# Generated by Django 5.0.3 on 2024-06-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
        ('tasks', '0003_rename_completed_at_task_done_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ability',
        ),
        migrations.AddField(
            model_name='task',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_outcome', to='abilities.outcome'),
        ),
    ]
