# Generated by Django 5.0.3 on 2024-07-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
