# Generated by Django 5.0.3 on 2024-07-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
        ('tasks', '0006_alter_task_description_alter_task_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpPerCountTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('xp', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_submit', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_per_count_task_outcome', to='abilities.outcome')),
            ],
        ),
    ]
