# Generated by Django 5.0.3 on 2024-07-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
        ('tasks', '0007_xppercounttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_task_outcome', to='abilities.outcome'),
        ),
    ]
