# Generated by Django 5.0.3 on 2024-07-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
        ('tasks', '0008_alter_task_outcome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='NormalTask',
        ),
    ]
