# Generated by Django 5.0.3 on 2024-07-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
        ('tasks', '0009_rename_task_normaltask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalTask',
            new_name='ClassicTask',
        ),
    ]
