# Generated by Django 5.0.3 on 2024-07-16 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_outcome_is_achieved_outcome_is_hided'),
        ('tasks', '0011_alter_classictask_outcome_counttask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('xp', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('longest_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_submit', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_tasks', to='abilities.outcome')),
            ],
        ),
    ]
