# Generated by Django 5.0.3 on 2024-07-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_outcome_is_achieved_outcome_is_hided'),
        ('tasks', '0012_timetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('xp', models.IntegerField(default=0)),
                ('penalty_xp', models.IntegerField(default=0)),
                ('report', models.CharField(max_length=1024, null=True)),
                ('penalty', models.CharField(choices=[('Half', 'Half XP loose'), ('Equal', 'Equal XP loose'), ('Double', 'Double XP loose'), ('Fourfold', 'Four fold XP loose')], max_length=32)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_aborted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_tasks', to='abilities.outcome')),
            ],
        ),
    ]
