# Generated by Django 5.0.7 on 2024-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_outcome_is_achieved_outcome_is_hided'),
        ('tasks', '0013_deadlinetask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassicTask',
            new_name='Classic',
        ),
        migrations.RenameModel(
            old_name='CountTask',
            new_name='Count',
        ),
        migrations.RenameModel(
            old_name='DeadlineTask',
            new_name='Deadline',
        ),
        migrations.RenameModel(
            old_name='TimeTask',
            new_name='Time',
        ),
    ]
