# Generated by Django 5.0.7 on 2024-07-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_rename_classictask_classic_rename_counttask_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='penalty',
            field=models.IntegerField(choices=[(0.5, 'Half XP loose'), (1, 'Equal XP loose'), (2, 'Double XP loose'), (4, 'Four fold XP loose')], default=1, max_length=32),
        ),
    ]
