# Generated by Django 5.0.7 on 2024-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_deadline_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='penalty',
            field=models.IntegerField(choices=[(0.5, 'Half XP loose'), (1, 'Equal XP loose'), (2, 'Double XP loose'), (4, 'Four fold XP loose')], default=1),
        ),
    ]
