# Generated by Django 5.0.7 on 2024-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_deadline_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='report',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
