# Generated by Django 5.0.7 on 2024-07-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_deadline_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='duration_hours',
        ),
    ]
