# Generated by Django 5.0.7 on 2024-08-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_deadline_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='description',
            field=models.TextField(),
        ),
    ]
