# Generated by Django 5.0.7 on 2024-08-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_classic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='is_added',
        ),
    ]
