# Generated by Django 5.2.7 on 2025-10-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outcomes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalecology',
            name='outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_ecology', to='outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='externalecology',
            name='outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_ecology', to='outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='outcomequestions',
            name='outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_questions', to='outcomes.outcome'),
        ),
    ]
