# Generated by Django 5.0.3 on 2024-06-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
        ('tasks', '0003_rename_completed_at_task_done_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ability',
            new_name='Outcome',
        ),
    ]
