# Generated by Django 5.0.7 on 2025-05-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
