# Generated by Django 5.2.7 on 2025-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_alter_outcome_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
