# Generated by Django 5.0.3 on 2024-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_rename_ability_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcome',
            name='is_hided',
            field=models.BooleanField(default=False),
        ),
    ]
