# Generated by Django 5.0.7 on 2024-08-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0004_outcome_achieved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='total_xp',
        ),
    ]
