# Generated by Django 5.0.7 on 2024-08-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0005_remove_outcome_total_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEcology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('q2', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('q3', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('q4', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_ecology', to='abilities.outcome')),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='ee_questions',
            field=models.OneToOneField(default='Not answered at all', on_delete=django.db.models.deletion.CASCADE, related_name='ee_questions', to='abilities.externalecology'),
        ),
        migrations.CreateModel(
            name='InternalEcology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('q2', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('q3', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('q4', models.CharField(default='Not answered yet.', max_length=128, null=True)),
                ('q5', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('q6', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('q7', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('q8', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_ecology', to='abilities.outcome')),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='ie_questions',
            field=models.OneToOneField(default='Not answered at all', on_delete=django.db.models.deletion.CASCADE, related_name='ie_questions', to='abilities.internalecology'),
        ),
        migrations.CreateModel(
            name='OutcomeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.CharField(default='Not answered yet.', max_length=128, null=True)),
                ('evidence', models.CharField(default='Not answered yet.', max_length=1024, null=True)),
                ('specific', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('resource', models.CharField(default='Not answered yet.', max_length=1024, null=True)),
                ('control', models.CharField(default='Not answered yet.', max_length=256, null=True)),
                ('identity', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('relation_with_other_outcomes', models.CharField(default='Not answered yet.', max_length=1028, null=True)),
                ('action', models.CharField(default='Not answered yet.', max_length=512, null=True)),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_questions', to='abilities.outcome')),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='o_questions',
            field=models.OneToOneField(default='Not answered at all', on_delete=django.db.models.deletion.CASCADE, related_name='o_questions', to='abilities.outcomequestions'),
        ),
    ]
