# Generated by Django 5.2.7 on 2025-10-18 17:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='animal',
            field=models.CharField(blank=True, choices=[('Owl', 'Owl'), ('Centipede', 'Centipede'), ('Dragon', 'Dragon'), ('Wolf', 'Wolf'), ('Lion', 'Lion'), ('Eagle', 'Eagle'), ('Butterfly', 'Butterfly'), ('Shark', 'Shark'), ('Jaguar', 'Jaguar'), ('Ant', 'Ant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='element',
            field=models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Void', 'Void'), ('Tornado', 'Tornado'), ('Lightning', 'Lightning'), ('Volcano', 'Volcano'), ('Earth', 'Earth'), ('Water', 'Water'), ('Air', 'Air')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_case_insensitive'),
        ),
    ]
