# Generated by Django 5.2.7 on 2025-10-16 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, and hyphens (no spaces).', regex='^[A-Za-z0-9\\-]+$')]),
        ),
    ]
